server:
  port: 8081
  servlet:
    context-path: /template
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://192.168.43.207:3306/zhuangruan?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  http:
    encoding:
      force: false

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zhongruan.template.**.entity
  configuration:
    map-underscore-to-camel-case: true



file:
  path:
    html: d:/file/html/
    word: d:/file/word/
    xml: d:/file/xml/
    ftl: d:/file/ftl/
    zip: d:/file/zip/
