server:
  port: 8081
  servlet:
    context-path: /template
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: username
    password: zhongruan123
    url: jdbc:mysql://127.0.0.1:3306/zhongruan?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zhongruan.template.**.entity
  configuration:
    map-underscore-to-camel-case: true



file:
  path:
    htm: e:/file/htm/
    html: e:/file/html/
    word: e:/file/word/
    xml: e:/file/xml/
    ftl: e:/file/ftl/
    zip: e:/file/zip/
